# Generated by Django 3.1.4 on 2021-03-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbmail',
            new_name='thumbnail',
        ),
    ]
