  version: '3.8'

  services:
    bd:
      image: postgres
      restart: always

      environment:
        - POSTGRES_DB=angeholly
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres



    ecommerce:
      build:  .
      container_name: ecommerce
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code

      ports:
        - "8000:8000"
      depends_on:
        - bd
      links:
        - bd:bd
    nginx:
      image: nginx
      ports:
        - "80:80"
      volumes:
        - "./nginx:/etc/nginx/conf.d"
        - "./media:/var/media"
      depends_on:
        - ecommerce